// src/web/components/ui/Modal.vue
<script lang="tsx">
import { onMounted, onUnmounted, ref } from 'vue';
import type { VNodeChild } from 'vue';
import { defineVueComponent } from '../../vue/component.ts';

import { Button } from './Button.vue';
import { FormField } from './FormField.vue';
import { TextInput, type TextInputHandle } from './TextInput.vue';

export type ModalProps = {
  title: string;
  description?: string;
  children?: VNodeChild;
  footer?: VNodeChild;
  onClose: () => void;
  closeLabel?: string;
  closeOnBackdrop?: boolean;
  className?: string;
};

/**
 * Small, application-owned dialog primitive. Keeping this outside the
 * automation view makes prompts and confirmations behave consistently across
 * the editor and the rest of the WebView UI.
 */
export const Modal = defineVueComponent<ModalProps>(
  ['title', 'description', 'children', 'footer', 'onClose', 'closeLabel', 'closeOnBackdrop', 'className'],
  (props) => {
  const dialogRef = ref<HTMLDivElement | null>(null);

  onMounted(() => {
    const previousFocus = document.activeElement as HTMLElement | null;
    const handleKeyDown = (event: KeyboardEvent): void => {
      if (event.key !== 'Escape') return;
      event.preventDefault();
      props.onClose();
    };

    document.addEventListener('keydown', handleKeyDown);
    const firstField = dialogRef.value?.querySelector<HTMLElement>(
      'input:not([disabled]), textarea:not([disabled]), select:not([disabled]), button:not(.ui-modal__close):not([disabled])',
    );
    (firstField ?? dialogRef.value)?.focus();

    onUnmounted(() => {
      document.removeEventListener('keydown', handleKeyDown);
      if (previousFocus?.isConnected) previousFocus.focus();
    });
  });

  return () => {
    const { title, description, children, footer, onClose, closeLabel = 'Close', closeOnBackdrop = true, className = '' } = props;
    return (
    <div
      class="ui-modal-backdrop"
      role="presentation"
      onMousedown={(event) => {
        if (closeOnBackdrop && event.target === event.currentTarget) onClose();
      }}
    >
      <div
        ref={dialogRef}
        class={`ui-modal-card ${className}`.trim()}
        role="dialog"
        aria-modal="true"
        aria-labelledby="ui-modal-title"
        tabindex={-1}
        onMousedown={(event) => event.stopPropagation()}
      >
        <header class="ui-modal-card__header">
          <h2 id="ui-modal-title" class="ui-modal-card__title">{title}</h2>
          <button
            type="button"
            class="ui-modal__close"
            aria-label={closeLabel}
            onClick={onClose}
          >
            ×
          </button>
        </header>
        {description ? <p class="ui-modal-card__description">{description}</p> : null}
        {children ? <div class="ui-modal-card__body">{children}</div> : null}
        {footer ? <footer class="ui-modal-card__footer">{footer}</footer> : null}
      </div>
    </div>
    );
  };
  },
);

export type TextPromptModalProps = {
  title: string;
  description?: string;
  label: string;
  initialValue?: string;
  placeholder?: string;
  confirmLabel: string;
  cancelLabel: string;
  requiredMessage: string;
  onConfirm: (value: string) => void;
  onClose: () => void;
};

export const TextPromptModal = defineVueComponent<TextPromptModalProps>(
  ['title', 'description', 'label', 'initialValue', 'placeholder', 'confirmLabel', 'cancelLabel', 'requiredMessage', 'onConfirm', 'onClose'],
  (props) => {
  const value = ref(props.initialValue ?? '');
  const error = ref('');
  const inputRef = ref<TextInputHandle | null>(null);

  const confirm = (): void => {
    const nextValue = value.value.trim();
    if (!nextValue) {
      error.value = props.requiredMessage;
      inputRef.value?.focus();
      return;
    }
    props.onConfirm(nextValue);
  };

  return () => {
    const { title, description, label, placeholder, confirmLabel, cancelLabel, onClose } = props;
    return (
    <Modal
      title={title}
      description={description}
      onClose={onClose}
      footer={
        <div class="ui-modal-card__actions">
        <Button variant="soft" onClick={onClose}>{cancelLabel}</Button>
          <Button variant="primary" onClick={confirm}>{confirmLabel}</Button>
        </div>
      }
    >
        <FormField label={label} error={error.value} required>
        <TextInput
          ref={inputRef}
          value={value.value}
          onValueChange={(nextValue) => {
            value.value = nextValue;
            if (error.value) error.value = '';
          }}
          placeholder={placeholder}
          required
          onEnter={confirm}
          spellCheck={false}
        />
      </FormField>
    </Modal>
    );
  };
  },
);

export type ConfirmModalProps = {
  title: string;
  description?: string;
  confirmLabel: string;
  cancelLabel: string;
  onConfirm: () => void;
  onClose: () => void;
  danger?: boolean;
};

export function ConfirmModal({
  title,
  description,
  confirmLabel,
  cancelLabel,
  onConfirm,
  onClose,
  danger = false,
}: ConfirmModalProps) {
  return (
    <Modal
      title={title}
      description={description}
      onClose={onClose}
      footer={
        <div class="ui-modal-card__actions">
          <Button variant="soft" onClick={onClose}>{cancelLabel}</Button>
          <Button variant={danger ? 'danger' : 'primary'} onClick={onConfirm}>{confirmLabel}</Button>
        </div>
      }
    />
  );
}

export default Modal;
</script>

// src/web/components/ui/Modal.tsx
import { useEffect, useRef, useState } from 'preact/hooks';
import type { ComponentChildren } from 'preact';

import { Button } from './Button.tsx';
import { FormField } from './FormField.tsx';
import { TextInput, type TextInputHandle } from './TextInput.tsx';

export type ModalProps = {
  title: string;
  description?: string;
  children?: ComponentChildren;
  footer?: ComponentChildren;
  onClose: () => void;
  closeLabel?: string;
  closeOnBackdrop?: boolean;
};

/**
 * Small, application-owned dialog primitive. Keeping this outside the
 * automation view makes prompts and confirmations behave consistently across
 * the editor and the rest of the WebView UI.
 */
export function Modal({
  title,
  description,
  children,
  footer,
  onClose,
  closeLabel = 'Close',
  closeOnBackdrop = true,
}: ModalProps) {
  const dialogRef = useRef<HTMLDivElement | null>(null);
  const onCloseRef = useRef(onClose);
  onCloseRef.current = onClose;

  useEffect(() => {
    const previousFocus = document.activeElement as HTMLElement | null;
    const handleKeyDown = (event: KeyboardEvent): void => {
      if (event.key !== 'Escape') return;
      event.preventDefault();
      onCloseRef.current();
    };

    document.addEventListener('keydown', handleKeyDown);
    const firstField = dialogRef.current?.querySelector<HTMLElement>(
      'input:not([disabled]), textarea:not([disabled]), select:not([disabled]), button:not(.ui-modal__close):not([disabled])',
    );
    (firstField ?? dialogRef.current)?.focus();

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
      if (previousFocus?.isConnected) previousFocus.focus();
    };
  }, []);

  return (
    <div
      className="ui-modal-backdrop"
      role="presentation"
      onMouseDown={(event) => {
        if (closeOnBackdrop && event.target === event.currentTarget) onClose();
      }}
    >
      <div
        ref={dialogRef}
        className="ui-modal-card"
        role="dialog"
        aria-modal="true"
        aria-labelledby="ui-modal-title"
        tabIndex={-1}
        onMouseDown={(event) => event.stopPropagation()}
      >
        <header className="ui-modal-card__header">
          <h2 id="ui-modal-title" className="ui-modal-card__title">{title}</h2>
          <button
            type="button"
            className="ui-modal__close"
            aria-label={closeLabel}
            onClick={onClose}
          >
            ×
          </button>
        </header>
        {description ? <p className="ui-modal-card__description">{description}</p> : null}
        {children ? <div className="ui-modal-card__body">{children}</div> : null}
        {footer ? <footer className="ui-modal-card__footer">{footer}</footer> : null}
      </div>
    </div>
  );
}

export type TextPromptModalProps = {
  title: string;
  description?: string;
  label: string;
  initialValue?: string;
  placeholder?: string;
  confirmLabel: string;
  cancelLabel: string;
  requiredMessage: string;
  onConfirm: (value: string) => void;
  onClose: () => void;
};

export function TextPromptModal({
  title,
  description,
  label,
  initialValue = '',
  placeholder,
  confirmLabel,
  cancelLabel,
  requiredMessage,
  onConfirm,
  onClose,
}: TextPromptModalProps) {
  const [value, setValue] = useState(initialValue);
  const [error, setError] = useState('');
  const inputRef = useRef<TextInputHandle | null>(null);

  const confirm = (): void => {
    const nextValue = value.trim();
    if (!nextValue) {
      setError(requiredMessage);
      inputRef.current?.focus();
      return;
    }
    onConfirm(nextValue);
  };

  return (
    <Modal
      title={title}
      description={description}
      onClose={onClose}
      footer={
        <div className="ui-modal-card__actions">
          <Button variant="soft" onClick={onClose}>{cancelLabel}</Button>
          <Button variant="primary" onClick={confirm}>{confirmLabel}</Button>
        </div>
      }
    >
      <FormField label={label} error={error} required>
        <TextInput
          ref={inputRef}
          value={value}
          onValueChange={(nextValue) => {
            setValue(nextValue);
            if (error) setError('');
          }}
          placeholder={placeholder}
          required
          onEnter={confirm}
          spellCheck={false}
        />
      </FormField>
    </Modal>
  );
}

export type ConfirmModalProps = {
  title: string;
  description?: string;
  confirmLabel: string;
  cancelLabel: string;
  onConfirm: () => void;
  onClose: () => void;
  danger?: boolean;
};

export function ConfirmModal({
  title,
  description,
  confirmLabel,
  cancelLabel,
  onConfirm,
  onClose,
  danger = false,
}: ConfirmModalProps) {
  return (
    <Modal
      title={title}
      description={description}
      onClose={onClose}
      footer={
        <div className="ui-modal-card__actions">
          <Button variant="soft" onClick={onClose}>{cancelLabel}</Button>
          <Button variant={danger ? 'danger' : 'primary'} onClick={onConfirm}>{confirmLabel}</Button>
        </div>
      }
    />
  );
}
