// src/web/components/node-editor/NodeConfigForm.vue
<script lang="tsx">
import { computed, ref, watch } from 'vue';
import { defineVueComponent } from '../../vue/component.ts';

import type {
  AutomationEvent,
  AutomationEventType,
  AutomationScriptAnalysis,
  AutomationScriptCompletion,
  JsonObject,
  JsonValue,
  NodeDefinition,
  WorkflowNode,
} from '../../../automation/types.ts';
import { TextInput } from '../ui/TextInput.vue';
import { NumberInput } from '../ui/NumberInput.vue';
import { Select } from '../ui/Select.vue';
import { Checkbox } from '../ui/Checkbox.vue';
import { TemplateField } from './TemplateField.vue';
import { getFetchUrlTemplates, getTemplateSuggestions, isLocalFetchUrl, type TemplateSuggestionScope } from './template-suggestions.ts';
import { AutocompletePortal } from './AutocompletePortal.vue';
import { WORKFLOW_EVENT_CHOICES } from './WorkflowWizardModal.vue';
import { asNumber, asString } from './graph.ts';
import { i18nText, t, type Locale } from '../../i18n.ts';
import { SchemaForm } from '../ui/SchemaForm.vue';

type NodeConfigFormProps = {
  locale: Locale;
  node: WorkflowNode;
  definition?: NodeDefinition;
  analysis?: AutomationScriptAnalysis;
  eventType?: AutomationEventType;
  lastEvent?: AutomationEvent;
  onChange: (config: JsonObject) => void;
  onAnalyzeScript: (nodeId: string, source: string, offset: number, eventType?: AutomationEventType) => void;
};

export function NodeConfigForm({ locale, node, definition, analysis, eventType, lastEvent, onChange, onAnalyzeScript }: NodeConfigFormProps) {
  const update = (key: string, value: JsonValue): void => onChange({ ...node.config, [key]: value });
  const config = node.config;
  const templateValues = (scope: TemplateSuggestionScope = 'message') => getTemplateSuggestions(eventType, locale, lastEvent, scope);

  if (!definition) {
    return <GenericConfigForm locale={locale} node={node} onChange={onChange} />;
  }

  switch (node.type) {
    case 'trigger.event':
      return (
        <div class="node-editor-form-stack">
          <Select
            label={t(locale, 'nodeEventType')}
            hint={t(locale, 'nodeEventTypeHint')}
            value={asString(config.eventType, 'tiktok.chat')}
            options={WORKFLOW_EVENT_CHOICES.map((choice) => ({ value: choice.value, label: i18nText(locale, choice.label) }))}
            onValueChange={(value) => update('eventType', value)}
          />
        </div>
      );
    case 'condition.compare':
      return (
        <div class="node-editor-form-stack">
          <TemplateField locale={locale}
            label={t(locale, 'nodeValuePath')}
            hint={t(locale, 'nodeValuePathHint')}
            value={asString(config.leftPath)}
            onValueChange={(value) => update('leftPath', value)}
            suggestions={templateValues('compare')}
            suggestionMode="path"
          />
          <Select
            label={t(locale, 'nodeOperator')}
            value={asString(config.operator, 'equals')}
            options={[
              ['equals', t(locale, 'nodeEquals')],
              ['not-equals', t(locale, 'nodeNotEquals')],
              ['greater-than', t(locale, 'nodeGreaterThan')],
              ['greater-or-equal', t(locale, 'nodeGreaterOrEqual')],
              ['less-than', t(locale, 'nodeLessThan')],
              ['less-or-equal', t(locale, 'nodeLessOrEqual')],
              ['contains', t(locale, 'nodeContains')],
              ['starts-with', t(locale, 'nodeStartsWith')],
              ['truthy', t(locale, 'nodeTruthy')],
              ['falsy', t(locale, 'nodeFalsy')],
            ].map(([value, label]) => ({ value: value ?? '', label: label ?? '' }))}
            onValueChange={(value) => update('operator', value)}
          />
          <TextInput label={t(locale, 'nodeCompareWith')} hint={t(locale, 'nodeCompareWithHint')} value={formatValue(config.right)} onValueChange={(value) => update('right', parseValue(value))} />
        </div>
      );
    case 'transform.template':
      return (
        <div class="node-editor-form-stack">
          <TemplateField locale={locale} label={t(locale, 'nodeTemplate')} hint={t(locale, 'nodeTemplateHint')} value={asString(config.template)} onValueChange={(value) => update('template', value)} suggestions={templateValues('message')} multiline rows={5} />
        </div>
      );
    case 'transform.script':
      return <ScriptConfigForm locale={locale} node={node} analysis={analysis} eventType={eventType} lastEvent={lastEvent} onChange={onChange} onAnalyzeScript={onAnalyzeScript} />;
    case 'control.delay':
      return (
        <div class="node-editor-form-stack">
          <NumberInput label={t(locale, 'nodeDelay')} hint={t(locale, 'nodeDelayHint')} value={asNumber(config.delayMs)} min={0} max={3_600_000} step={100} suffix="ms" onValueChange={(value) => update('delayMs', value)} />
        </div>
      );
    case 'control.cooldown':
      return (
        <div class="node-editor-form-stack">
          <NumberInput label={t(locale, 'nodeDuration')} hint={t(locale, 'nodeCooldownHint')} value={asNumber(config.durationMs)} min={0} max={86_400_000} step={100} suffix="ms" onValueChange={(value) => update('durationMs', value)} />
          <TemplateField locale={locale} label={t(locale, 'nodeCooldownKey')} value={asString(config.key)} onValueChange={(value) => update('key', value)} suggestions={templateValues('identity')} />
        </div>
      );
    case 'action.log':
      return (
        <div class="node-editor-form-stack">
          <TemplateField locale={locale} label={t(locale, 'nodeMessage')} hint={t(locale, 'nodeTemplateHint')} value={asString(config.message)} onValueChange={(value) => update('message', value)} suggestions={templateValues('message')} multiline rows={5} />
        </div>
      );
    case 'action.http':
      return <HttpConfigForm locale={locale} eventType={eventType} lastEvent={lastEvent} config={config} onChange={update} />;
    case 'action.play-sound':
      return (
        <div class="node-editor-form-stack">
          <TemplateField locale={locale} label={t(locale, 'nodeFilePath')} hint={t(locale, 'nodeFilePathHint')} value={asString(config.filePath)} onValueChange={(value) => update('filePath', value)} suggestions={templateValues('sound-file')} />
          <NumberInput label={t(locale, 'nodeVolume')} value={asNumber(config.volume, 1)} min={0} max={1} step={0.05} onValueChange={(value) => update('volume', value)} />
          <Select label={t(locale, 'nodeOverlap')} value={asString(config.overlap, 'allow')} options={[{ value: 'allow', label: t(locale, 'nodeAllowOverlap') }, { value: 'restart', label: t(locale, 'nodeRestartOverlap') }, { value: 'drop', label: t(locale, 'nodeDropOverlap') }]} onValueChange={(value) => update('overlap', value)} />
        </div>
      );
    case 'action.tts':
      return (
        <div class="node-editor-form-stack">
          <TemplateField locale={locale} label={t(locale, 'nodeText')} hint={t(locale, 'nodeTemplateHint')} value={asString(config.text)} onValueChange={(value) => update('text', value)} suggestions={templateValues('text')} multiline rows={5} />
          <TextInput label={t(locale, 'nodeVoice')} value={asString(config.voice, 'M1')} onValueChange={(value) => update('voice', value)} />
          <Select label={t(locale, 'nodeLanguage')} value={asString(config.lang, 'en')} options={[{ value: 'en', label: 'English' }, { value: 'es', label: 'Español' }]} onValueChange={(value) => update('lang', value)} />
          <Select label={t(locale, 'nodeAudioFormat')} value={asString(config.format, 'wav')} options={[{ value: 'wav', label: 'WAV' }, { value: 'ogg', label: 'OGG' }]} onValueChange={(value) => update('format', value)} />
        </div>
      );
    case 'action.adjust-points':
      return (
        <div class="node-editor-form-stack">
          <TemplateField locale={locale} label={t(locale, 'nodeViewer')} hint={t(locale, 'nodeViewerHint')} value={asString(config.uniqueId)} onValueChange={(value) => update('uniqueId', value)} suggestions={templateValues('identity')} />
          <NumberInput label={t(locale, 'nodeDelta')} value={asNumber(config.delta, 10)} step={1} onValueChange={(value) => update('delta', value)} />
        </div>
      );
    default:
      return <GenericConfigForm locale={locale} node={node} definition={definition} onChange={onChange} />;
  }
}

const ScriptConfigForm = defineVueComponent<NodeConfigFormProps>(
  ['locale', 'node', 'analysis', 'eventType', 'lastEvent', 'onChange', 'onAnalyzeScript'],
  (props) => {
  const source = computed(() => asString(props.node.config.source));
  const cursor = ref(source.value.length);
  const completionIndex = ref(0);
  const completionOpen = ref(true);
  const textareaRef = ref<HTMLTextAreaElement | null>(null);
  const completionAnchorRef = ref<HTMLDivElement | null>(null);
  const completionKey = computed(() => props.analysis?.completions.map((completion) => `${completion.label}:${completion.detail ?? ''}`).join('|') ?? '');
  const visibleCompletions = computed(() => props.analysis?.completions.slice(0, 12) ?? []);

  watch(() => [props.node.id, source.value], () => { cursor.value = source.value.length; });
  watch(completionKey, () => {
    completionIndex.value = 0;
    completionOpen.value = visibleCompletions.value.length > 0;
  });

  const change = (nextSource: string, nextCursor: number): void => {
    cursor.value = nextCursor;
    props.onChange({ ...props.node.config, source: nextSource });
    props.onAnalyzeScript(props.node.id, nextSource, nextCursor, props.eventType);
  };

  const applyCompletion = (completion: AutomationScriptCompletion): void => {
    const textarea = textareaRef.value;
    const offset = textarea?.selectionStart ?? cursor.value;
    const before = source.value.slice(0, offset);
    const match = before.match(/[A-Za-z0-9_$]*$/);
    const start = offset - (match?.[0]?.length ?? 0);
    const nextSource = `${source.value.slice(0, start)}${completion.label}${source.value.slice(offset)}`;
    const nextOffset = start + completion.label.length;
    change(nextSource, nextOffset);
    completionOpen.value = false;
    requestAnimationFrame(() => {
      textareaRef.value?.focus();
      textareaRef.value?.setSelectionRange(nextOffset, nextOffset);
    });
  };

  const handleCompletionKeydown = (event: KeyboardEvent): void => {
    const completions = visibleCompletions.value;
    if (!completionOpen.value || completions.length === 0) return;
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      completionIndex.value = (completionIndex.value + 1) % completions.length;
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      completionIndex.value = (completionIndex.value - 1 + completions.length) % completions.length;
    } else if (event.key === 'Tab' || event.key === 'Enter') {
      event.preventDefault();
      const selected = completions[completionIndex.value];
      if (selected) applyCompletion(selected);
    } else if (event.key === 'Escape') {
      event.preventDefault();
      completionOpen.value = false;
    }
  };

  return () => (
    <div class="node-editor-form-stack">
      <div class="node-editor-script-context">
        <span>{t(props.locale, 'scriptEditor')}</span>
        <small>{props.lastEvent ? `${t(props.locale, 'lastEventContext')}: ${props.lastEvent.type}` : t(props.locale, 'noLastEventContext')}</small>
      </div>
      <div class={`plg-float ${source.value.trim().length > 0 ? 'is-filled' : ''}`}>
        <div class="plg-float__control plg-float__control--textarea">
          <div ref={completionAnchorRef} class="node-editor-script-editor" style={{ flex: 1, display: 'flex' }}>
            <textarea
              ref={textareaRef}
              class="node-editor-form-textarea node-editor-form-textarea--code"
              style={{ border: 'none', background: 'transparent', flex: 1 }}
              value={source.value}
              rows={12}
              spellcheck={false}
              placeholder=" "
              aria-label={t(props.locale, 'scriptEditor')}
              onFocus={() => { completionOpen.value = true; }}
              onKeydown={handleCompletionKeydown}
              onInput={(event) => {
                const target = event.currentTarget as HTMLTextAreaElement;
                change(target.value, target.selectionStart ?? target.value.length);
              }}
              onKeyup={(event) => {
                if (event.key === 'ArrowDown' || event.key === 'ArrowUp' || event.key === 'Tab' || event.key === 'Enter' || event.key === 'Escape') return;
                const target = event.currentTarget as HTMLTextAreaElement;
                cursor.value = target.selectionStart ?? source.value.length;
                props.onAnalyzeScript(props.node.id, source.value, target.selectionStart ?? source.value.length, props.eventType);
              }}
              onClick={(event) => {
                const target = event.currentTarget as HTMLTextAreaElement;
                cursor.value = target.selectionStart ?? source.value.length;
                props.onAnalyzeScript(props.node.id, source.value, target.selectionStart ?? source.value.length, props.eventType);
              }}
            />
            <AutocompletePortal anchorRef={completionAnchorRef} cursorRef={textareaRef} cursorOffset={cursor.value} open={completionOpen.value && visibleCompletions.value.length > 0}>
              <div class="node-editor-code-completions" role="listbox">
                {visibleCompletions.value.map((completion, index) => (
                  <button
                    key={`${completion.kind}:${completion.label}`}
                    type="button"
                    role="option"
                    aria-selected={index === completionIndex.value}
                    class={index === completionIndex.value ? 'is-selected' : ''}
                    title={completion.documentation ?? completion.detail ?? completion.label}
                    onMousedown={(event) => event.preventDefault()}
                    onMouseenter={() => { completionIndex.value = index; }}
                    onClick={() => applyCompletion(completion)}
                  >
                    <strong>{completion.label}</strong>
                    <span>{completion.detail ?? completion.kind}</span>
                    {completion.valueSource === 'live-event' && completion.value !== undefined ? <code>{formatEditorValue(completion.value)}</code> : null}
                  </button>
                ))}
                <small>↑ ↓ {t(props.locale, 'navigate')} · Tab {t(props.locale, 'insertAction')}</small>
              </div>
            </AutocompletePortal>
          </div>
          <label class="plg-float__label">
            {t(props.locale, 'scriptEditor')}
          </label>
        </div>
      </div>
      {props.analysis?.diagnostics.length ? (
        <div class="node-editor-diagnostics" role="status">
          {props.analysis.diagnostics.map((diagnostic, index) => <div key={`${diagnostic.line}:${diagnostic.column}:${index}`} class="node-editor-diagnostic"><span>{diagnostic.line}:{diagnostic.column}</span> {diagnostic.message}</div>)}
        </div>
      ) : null}
      {props.analysis?.hover ? (
        <div class="node-editor-hover-card" role="status">
          <strong>{props.analysis.hover.detail}</strong>
          <span>{props.analysis.hover.documentation}</span>
          {props.analysis.hover.valueSource === 'live-event' && props.analysis.hover.value !== undefined
            ? props.analysis.hover.path === 'event.data'
              ? <pre>{formatEditorValue(props.analysis.hover.value, true)}</pre>
              : <code>{formatEditorValue(props.analysis.hover.value)}</code>
            : null}
        </div>
      ) : null}
    </div>
  );
  },
);

function HttpConfigForm({ locale, eventType, lastEvent, config, onChange }: { locale: Locale; eventType?: AutomationEventType; lastEvent?: AutomationEvent; config: JsonObject; onChange: (key: string, value: JsonValue) => void }) {
  const templateValues = (scope: TemplateSuggestionScope) => getTemplateSuggestions(eventType, locale, lastEvent, scope);
  const urlValue = asString(config.url);
  const allowPrivate = config.allowPrivateNetwork === true || config.allowPrivateNetwork === 'true';
  const urlPresets = getFetchUrlTemplates();
  return (
    <div class="node-editor-form-stack">
      <Select label={t(locale, 'nodeMethod')} value={asString(config.method, 'GET')} options={['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map((value) => ({ value, label: value }))} onValueChange={(value) => onChange('method', value)} />
      <TemplateField locale={locale} label={t(locale, 'nodeUrl')} hint={t(locale, 'nodeTemplateHint')} value={urlValue} onValueChange={(value) => onChange('url', value)} suggestions={templateValues('http-url')} bareWordTrigger={false} urlPresets={urlPresets} />
      {urlValue.trim() && isLocalFetchUrl(urlValue) && !allowPrivate && (
        <p class="act-localhint" role="note">
          <span>{t(locale, 'behavior.editor.localNetHint')}</span>
          <button type="button" class="act-preset" onClick={() => onChange('allowPrivateNetwork', true)}>
            {t(locale, 'behavior.editor.enableLocalNet')}
          </button>
        </p>
      )}
      <TemplateField locale={locale} label={t(locale, 'nodeRequestBody')} value={asString(config.body)} onValueChange={(value) => onChange('body', value)} suggestions={templateValues('http-data')} multiline rows={4} />
      <TemplateField locale={locale} label={t(locale, 'nodeHeaders')} hint={t(locale, 'nodeHeadersHint')} value={headersToText(config.headers)} onValueChange={(value) => onChange('headers', parseHeaders(value))} suggestions={templateValues('http-data')} multiline rows={4} />
      <NumberInput label={t(locale, 'nodeTimeout')} value={asNumber(config.timeoutMs, 10000)} min={100} max={120000} step={100} suffix="ms" onValueChange={(value) => onChange('timeoutMs', value)} />
      <Select label={t(locale, 'nodeResponseType')} value={asString(config.responseType, 'auto')} options={[{ value: 'auto', label: 'Auto' }, { value: 'json', label: 'JSON' }, { value: 'text', label: 'Text' }, { value: 'bytes', label: 'Bytes' }]} onValueChange={(value) => onChange('responseType', value)} />
      <Select label={t(locale, 'nodeRedirect')} value={asString(config.redirect, 'error')} options={[{ value: 'error', label: t(locale, 'nodeBlockRedirects') }, { value: 'follow', label: t(locale, 'nodeFollowRedirects') }]} onValueChange={(value) => onChange('redirect', value)} />
      <Checkbox checked={allowPrivate} onCheckedChange={(value) => onChange('allowPrivateNetwork', value)} label={t(locale, 'nodeAllowPrivateNetwork')} />
    </div>
  );
}

function GenericConfigForm({ locale, node, definition, onChange }: { locale: Locale; node: WorkflowNode; definition?: NodeDefinition; onChange: (config: JsonObject) => void }) {
  if (!definition || !isJsonObject(definition.configSchema)) return <GenericConfigFormNoForm locale={locale} />;
  const properties = definition.configSchema.properties;
  if (!properties || typeof properties !== 'object' || Array.isArray(properties) || Object.keys(properties).length === 0) return <GenericConfigFormNoForm locale={locale} />;
  return <SchemaForm locale={locale} schema={definition.configSchema} value={node.config} onChange={onChange} />;
}

function formatValue(value: JsonValue | undefined): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'object') return '';
  return String(value);
}

function formatEditorValue(value: JsonValue, pretty = false): string {
  if (typeof value === 'string') return JSON.stringify(value);
  if (value === null) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  try {
    const serialized = JSON.stringify(value, pretty ? null : undefined, pretty ? 2 : undefined) ?? String(value);
    if (pretty) return serialized.length > 8_000 ? `${serialized.slice(0, 7_997)}...` : serialized;
    return serialized.length > 140 ? `${serialized.slice(0, 137)}...` : serialized;
  } catch {
    return String(value);
  }
}

function parseValue(value: string): JsonValue {
  const trimmed = value.trim();
  if (!trimmed) return '';
  if (trimmed === 'true') return true;
  if (trimmed === 'false') return false;
  const number = Number(trimmed);
  return Number.isFinite(number) && trimmed !== '' ? number : value;
}

function headersToText(value: JsonValue | undefined): string {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return '';
  return Object.entries(value).map(([key, raw]) => `${key}: ${typeof raw === 'string' ? raw : String(raw ?? '')}`).join('\n');
}

function parseHeaders(value: string): JsonObject {
  const headers: JsonObject = {};
  for (const line of value.split('\n')) {
    const separator = line.indexOf(':');
    if (separator <= 0) continue;
    const key = line.slice(0, separator).trim();
    if (key) headers[key] = line.slice(separator + 1).trim();
  }
  return headers;
}

function isJsonObject(value: JsonValue | undefined): value is JsonObject {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function GenericConfigFormNoForm({ locale }: { locale: Locale }) {
  return <p class="node-editor-form-empty">{t(locale, 'nodeNoForm')}</p>;
}

export default NodeConfigForm;
</script>

// src/web/components/node-editor/NodeConfigForm.tsx
import { useEffect, useMemo, useRef, useState } from 'preact/hooks';

import type {
  AutomationEvent,
  AutomationEventType,
  AutomationScriptAnalysis,
  AutomationScriptCompletion,
  JsonObject,
  JsonValue,
  NodeDefinition,
  WorkflowNode,
} from '../../../automation/types.ts';
import { TextInput } from '../ui/TextInput.tsx';
import { NumberInput } from '../ui/NumberInput.tsx';
import { Select } from '../ui/Select.tsx';
import { Checkbox } from '../ui/Checkbox.tsx';
import { TemplateField } from './TemplateField.tsx';
import { getFetchUrlTemplates, getTemplateSuggestions, isLocalFetchUrl, type TemplateSuggestionScope } from './template-suggestions.ts';
import { AutocompletePortal } from './AutocompletePortal.tsx';
import { WORKFLOW_EVENT_CHOICES } from './WorkflowWizardModal.tsx';
import { asNumber, asString } from './graph.ts';
import { i18nText, t, type Locale } from '../../i18n.ts';
import { SchemaForm } from '../ui/SchemaForm.tsx';

type NodeConfigFormProps = {
  locale: Locale;
  node: WorkflowNode;
  definition?: NodeDefinition;
  analysis?: AutomationScriptAnalysis;
  eventType?: AutomationEventType;
  lastEvent?: AutomationEvent;
  onChange: (config: JsonObject) => void;
  onAnalyzeScript: (nodeId: string, source: string, offset: number, eventType?: AutomationEventType) => void;
};

export function NodeConfigForm({ locale, node, definition, analysis, eventType, lastEvent, onChange, onAnalyzeScript }: NodeConfigFormProps) {
  const update = (key: string, value: JsonValue): void => onChange({ ...node.config, [key]: value });
  const config = node.config;
  const templateValues = (scope: TemplateSuggestionScope = 'message') => getTemplateSuggestions(eventType, locale, lastEvent, scope);

  if (!definition) {
    return <GenericConfigForm locale={locale} node={node} onChange={onChange} />;
  }

  switch (node.type) {
    case 'trigger.event':
      return (
        <div className="node-editor-form-stack">
          <Select
            label={t(locale, 'nodeEventType')}
            hint={t(locale, 'nodeEventTypeHint')}
            value={asString(config.eventType, 'tiktok.chat')}
            options={WORKFLOW_EVENT_CHOICES.map((choice) => ({ value: choice.value, label: i18nText(locale, choice.label) }))}
            onValueChange={(value) => update('eventType', value)}
          />
        </div>
      );
    case 'condition.compare':
      return (
        <div className="node-editor-form-stack">
          <TemplateField locale={locale}
            label={t(locale, 'nodeValuePath')}
            hint={t(locale, 'nodeValuePathHint')}
            value={asString(config.leftPath)}
            onValueChange={(value) => update('leftPath', value)}
            suggestions={templateValues('compare')}
            suggestionMode="path"
          />
          <Select
            label={t(locale, 'nodeOperator')}
            value={asString(config.operator, 'equals')}
            options={[
              ['equals', t(locale, 'nodeEquals')],
              ['not-equals', t(locale, 'nodeNotEquals')],
              ['greater-than', t(locale, 'nodeGreaterThan')],
              ['greater-or-equal', t(locale, 'nodeGreaterOrEqual')],
              ['less-than', t(locale, 'nodeLessThan')],
              ['less-or-equal', t(locale, 'nodeLessOrEqual')],
              ['contains', t(locale, 'nodeContains')],
              ['starts-with', t(locale, 'nodeStartsWith')],
              ['truthy', t(locale, 'nodeTruthy')],
              ['falsy', t(locale, 'nodeFalsy')],
            ].map(([value, label]) => ({ value: value ?? '', label: label ?? '' }))}
            onValueChange={(value) => update('operator', value)}
          />
          <TextInput label={t(locale, 'nodeCompareWith')} hint={t(locale, 'nodeCompareWithHint')} value={formatValue(config.right)} onValueChange={(value) => update('right', parseValue(value))} />
        </div>
      );
    case 'transform.template':
      return (
        <div className="node-editor-form-stack">
          <TemplateField locale={locale} label={t(locale, 'nodeTemplate')} hint={t(locale, 'nodeTemplateHint')} value={asString(config.template)} onValueChange={(value) => update('template', value)} suggestions={templateValues('message')} multiline rows={5} />
        </div>
      );
    case 'transform.script':
      return <ScriptConfigForm locale={locale} node={node} analysis={analysis} eventType={eventType} lastEvent={lastEvent} onChange={onChange} onAnalyzeScript={onAnalyzeScript} />;
    case 'control.delay':
      return (
        <div className="node-editor-form-stack">
          <NumberInput label={t(locale, 'nodeDelay')} hint={t(locale, 'nodeDelayHint')} value={asNumber(config.delayMs)} min={0} max={3_600_000} step={100} suffix="ms" onValueChange={(value) => update('delayMs', value)} />
        </div>
      );
    case 'control.cooldown':
      return (
        <div className="node-editor-form-stack">
          <NumberInput label={t(locale, 'nodeDuration')} hint={t(locale, 'nodeCooldownHint')} value={asNumber(config.durationMs)} min={0} max={86_400_000} step={100} suffix="ms" onValueChange={(value) => update('durationMs', value)} />
          <TemplateField locale={locale} label={t(locale, 'nodeCooldownKey')} value={asString(config.key)} onValueChange={(value) => update('key', value)} suggestions={templateValues('identity')} />
        </div>
      );
    case 'action.log':
      return (
        <div className="node-editor-form-stack">
          <TemplateField locale={locale} label={t(locale, 'nodeMessage')} hint={t(locale, 'nodeTemplateHint')} value={asString(config.message)} onValueChange={(value) => update('message', value)} suggestions={templateValues('message')} multiline rows={5} />
        </div>
      );
    case 'action.http':
      return <HttpConfigForm locale={locale} eventType={eventType} lastEvent={lastEvent} config={config} onChange={update} />;
    case 'action.play-sound':
      return (
        <div className="node-editor-form-stack">
          <TemplateField locale={locale} label={t(locale, 'nodeFilePath')} hint={t(locale, 'nodeFilePathHint')} value={asString(config.filePath)} onValueChange={(value) => update('filePath', value)} suggestions={templateValues('sound-file')} />
          <NumberInput label={t(locale, 'nodeVolume')} value={asNumber(config.volume, 1)} min={0} max={1} step={0.05} onValueChange={(value) => update('volume', value)} />
          <Select label={t(locale, 'nodeOverlap')} value={asString(config.overlap, 'allow')} options={[{ value: 'allow', label: t(locale, 'nodeAllowOverlap') }, { value: 'restart', label: t(locale, 'nodeRestartOverlap') }, { value: 'drop', label: t(locale, 'nodeDropOverlap') }]} onValueChange={(value) => update('overlap', value)} />
        </div>
      );
    case 'action.tts':
      return (
        <div className="node-editor-form-stack">
          <TemplateField locale={locale} label={t(locale, 'nodeText')} hint={t(locale, 'nodeTemplateHint')} value={asString(config.text)} onValueChange={(value) => update('text', value)} suggestions={templateValues('text')} multiline rows={5} />
          <TextInput label={t(locale, 'nodeVoice')} value={asString(config.voice, 'M1')} onValueChange={(value) => update('voice', value)} />
          <Select label={t(locale, 'nodeLanguage')} value={asString(config.lang, 'en')} options={[{ value: 'en', label: 'English' }, { value: 'es', label: 'Español' }]} onValueChange={(value) => update('lang', value)} />
          <Select label={t(locale, 'nodeAudioFormat')} value={asString(config.format, 'wav')} options={[{ value: 'wav', label: 'WAV' }, { value: 'ogg', label: 'OGG' }]} onValueChange={(value) => update('format', value)} />
        </div>
      );
    case 'action.adjust-points':
      return (
        <div className="node-editor-form-stack">
          <TemplateField locale={locale} label={t(locale, 'nodeViewer')} hint={t(locale, 'nodeViewerHint')} value={asString(config.uniqueId)} onValueChange={(value) => update('uniqueId', value)} suggestions={templateValues('identity')} />
          <NumberInput label={t(locale, 'nodeDelta')} value={asNumber(config.delta, 10)} step={1} onValueChange={(value) => update('delta', value)} />
        </div>
      );
    default:
      return <GenericConfigForm locale={locale} node={node} definition={definition} onChange={onChange} />;
  }
}

function ScriptConfigForm({ locale, node, analysis, eventType, lastEvent, onChange, onAnalyzeScript }: NodeConfigFormProps) {
  const source = asString(node.config.source);
  const [cursor, setCursor] = useState(source.length);
  const [completionIndex, setCompletionIndex] = useState(0);
  const [completionOpen, setCompletionOpen] = useState(true);
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);
  const completionAnchorRef = useRef<HTMLDivElement | null>(null);
  const completionKey = analysis?.completions.map((completion) => `${completion.label}:${completion.detail ?? ''}`).join('|') ?? '';
  const visibleCompletions = analysis?.completions.slice(0, 12) ?? [];

  useEffect(() => setCursor(source.length), [node.id, source]);
  useEffect(() => {
    setCompletionIndex(0);
    setCompletionOpen(visibleCompletions.length > 0);
  }, [completionKey]);

  const change = (nextSource: string, nextCursor: number): void => {
    setCursor(nextCursor);
    onChange({ ...node.config, source: nextSource });
    onAnalyzeScript(node.id, nextSource, nextCursor, eventType);
  };

  const applyCompletion = (completion: AutomationScriptCompletion): void => {
    const textarea = textareaRef.current;
    const offset = textarea?.selectionStart ?? cursor;
    const before = source.slice(0, offset);
    const match = before.match(/[A-Za-z0-9_$]*$/);
    const start = offset - (match?.[0]?.length ?? 0);
    const nextSource = `${source.slice(0, start)}${completion.label}${source.slice(offset)}`;
    const nextOffset = start + completion.label.length;
    change(nextSource, nextOffset);
    setCompletionOpen(false);
    requestAnimationFrame(() => {
      textareaRef.current?.focus();
      textareaRef.current?.setSelectionRange(nextOffset, nextOffset);
    });
  };

  const handleCompletionKeyDown = (event: KeyboardEvent): void => {
    const completions = visibleCompletions;
    if (!completionOpen || completions.length === 0) return;
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      setCompletionIndex((current) => (current + 1) % completions.length);
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      setCompletionIndex((current) => (current - 1 + completions.length) % completions.length);
    } else if (event.key === 'Tab' || event.key === 'Enter') {
      event.preventDefault();
      const selected = completions[completionIndex];
      if (selected) applyCompletion(selected);
    } else if (event.key === 'Escape') {
      event.preventDefault();
      setCompletionOpen(false);
    }
  };

  return (
    <div className="node-editor-form-stack">
      <div className="node-editor-script-context">
        <span>{t(locale, 'scriptEditor')}</span>
        <small>{lastEvent ? `${t(locale, 'lastEventContext')}: ${lastEvent.type}` : t(locale, 'noLastEventContext')}</small>
      </div>
      <div className={`plg-float ${source.trim().length > 0 ? 'is-filled' : ''}`}>
        <div className="plg-float__control plg-float__control--textarea">
          <div ref={completionAnchorRef} className="node-editor-script-editor" style={{ flex: 1, display: 'flex' }}>
            <textarea
              ref={textareaRef}
              className="node-editor-form-textarea node-editor-form-textarea--code"
              style={{ border: 'none', background: 'transparent', flex: 1 }}
              value={source}
              rows={12}
              spellcheck={false}
              placeholder=" "
              aria-label={t(locale, 'scriptEditor')}
              onFocus={() => setCompletionOpen(true)}
              onKeyDown={handleCompletionKeyDown}
              onInput={(event) => {
                const target = event.currentTarget;
                change(target.value, target.selectionStart ?? target.value.length);
              }}
              onKeyUp={(event) => {
                if (event.key === 'ArrowDown' || event.key === 'ArrowUp' || event.key === 'Tab' || event.key === 'Enter' || event.key === 'Escape') return;
                setCursor(event.currentTarget.selectionStart ?? source.length);
                onAnalyzeScript(node.id, source, event.currentTarget.selectionStart ?? source.length, eventType);
              }}
              onClick={(event) => {
                setCursor(event.currentTarget.selectionStart ?? source.length);
                onAnalyzeScript(node.id, source, event.currentTarget.selectionStart ?? source.length, eventType);
              }}
            />
            <AutocompletePortal anchorRef={completionAnchorRef} cursorRef={textareaRef} cursorOffset={cursor} open={completionOpen && visibleCompletions.length > 0}>
              <div className="node-editor-code-completions" role="listbox">
                {visibleCompletions.map((completion, index) => (
                  <button
                    key={`${completion.kind}:${completion.label}`}
                    type="button"
                    role="option"
                    aria-selected={index === completionIndex}
                    className={index === completionIndex ? 'is-selected' : ''}
                    title={completion.documentation ?? completion.detail ?? completion.label}
                    onMouseDown={(event) => event.preventDefault()}
                    onMouseEnter={() => setCompletionIndex(index)}
                    onClick={() => applyCompletion(completion)}
                  >
                    <strong>{completion.label}</strong>
                    <span>{completion.detail ?? completion.kind}</span>
                    {completion.valueSource === 'live-event' && completion.value !== undefined ? <code>{formatEditorValue(completion.value)}</code> : null}
                  </button>
                ))}
                <small>↑ ↓ {t(locale, 'navigate')} · Tab {t(locale, 'insertAction')}</small>
              </div>
            </AutocompletePortal>
          </div>
          <label className="plg-float__label">
            {t(locale, 'scriptEditor')}
          </label>
        </div>
      </div>
      {analysis?.diagnostics.length ? (
        <div className="node-editor-diagnostics" role="status">
          {analysis.diagnostics.map((diagnostic, index) => <div key={`${diagnostic.line}:${diagnostic.column}:${index}`} className="node-editor-diagnostic"><span>{diagnostic.line}:{diagnostic.column}</span> {diagnostic.message}</div>)}
        </div>
      ) : null}
      {analysis?.hover ? (
        <div className="node-editor-hover-card" role="status">
          <strong>{analysis.hover.detail}</strong>
          <span>{analysis.hover.documentation}</span>
          {analysis.hover.valueSource === 'live-event' && analysis.hover.value !== undefined
            ? analysis.hover.path === 'event.data'
              ? <pre>{formatEditorValue(analysis.hover.value, true)}</pre>
              : <code>{formatEditorValue(analysis.hover.value)}</code>
            : null}
        </div>
      ) : null}
    </div>
  );
}

function HttpConfigForm({ locale, eventType, lastEvent, config, onChange }: { locale: Locale; eventType?: AutomationEventType; lastEvent?: AutomationEvent; config: JsonObject; onChange: (key: string, value: JsonValue) => void }) {
  const templateValues = (scope: TemplateSuggestionScope) => getTemplateSuggestions(eventType, locale, lastEvent, scope);
  const urlValue = asString(config.url);
  const allowPrivate = config.allowPrivateNetwork === true || config.allowPrivateNetwork === 'true';
  const urlPresets = useMemo(() => getFetchUrlTemplates(), []);
  return (
    <div className="node-editor-form-stack">
      <Select label={t(locale, 'nodeMethod')} value={asString(config.method, 'GET')} options={['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map((value) => ({ value, label: value }))} onValueChange={(value) => onChange('method', value)} />
      <TemplateField locale={locale} label={t(locale, 'nodeUrl')} hint={t(locale, 'nodeTemplateHint')} value={urlValue} onValueChange={(value) => onChange('url', value)} suggestions={templateValues('http-url')} bareWordTrigger={false} urlPresets={urlPresets} />
      {urlValue.trim() && isLocalFetchUrl(urlValue) && !allowPrivate && (
        <p className="act-localhint" role="note">
          <span>{t(locale, 'behavior.editor.localNetHint')}</span>
          <button type="button" className="act-preset" onClick={() => onChange('allowPrivateNetwork', true)}>
            {t(locale, 'behavior.editor.enableLocalNet')}
          </button>
        </p>
      )}
      <TemplateField locale={locale} label={t(locale, 'nodeRequestBody')} value={asString(config.body)} onValueChange={(value) => onChange('body', value)} suggestions={templateValues('http-data')} multiline rows={4} />
      <TemplateField locale={locale} label={t(locale, 'nodeHeaders')} hint={t(locale, 'nodeHeadersHint')} value={headersToText(config.headers)} onValueChange={(value) => onChange('headers', parseHeaders(value))} suggestions={templateValues('http-data')} multiline rows={4} />
      <NumberInput label={t(locale, 'nodeTimeout')} value={asNumber(config.timeoutMs, 10000)} min={100} max={120000} step={100} suffix="ms" onValueChange={(value) => onChange('timeoutMs', value)} />
      <Select label={t(locale, 'nodeResponseType')} value={asString(config.responseType, 'auto')} options={[{ value: 'auto', label: 'Auto' }, { value: 'json', label: 'JSON' }, { value: 'text', label: 'Text' }, { value: 'bytes', label: 'Bytes' }]} onValueChange={(value) => onChange('responseType', value)} />
      <Select label={t(locale, 'nodeRedirect')} value={asString(config.redirect, 'error')} options={[{ value: 'error', label: t(locale, 'nodeBlockRedirects') }, { value: 'follow', label: t(locale, 'nodeFollowRedirects') }]} onValueChange={(value) => onChange('redirect', value)} />
      <Checkbox checked={allowPrivate} onCheckedChange={(value) => onChange('allowPrivateNetwork', value)} label={t(locale, 'nodeAllowPrivateNetwork')} />
    </div>
  );
}

function GenericConfigForm({ locale, node, definition, onChange }: { locale: Locale; node: WorkflowNode; definition?: NodeDefinition; onChange: (config: JsonObject) => void }) {
  if (!definition || !isJsonObject(definition.configSchema)) return <GenericConfigFormNoForm locale={locale} />;
  const properties = definition.configSchema.properties;
  if (!properties || typeof properties !== 'object' || Array.isArray(properties) || Object.keys(properties).length === 0) return <GenericConfigFormNoForm locale={locale} />;
  return <SchemaForm locale={locale} schema={definition.configSchema} value={node.config} onChange={onChange} />;
}

function formatValue(value: JsonValue | undefined): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'object') return '';
  return String(value);
}

function formatEditorValue(value: JsonValue, pretty = false): string {
  if (typeof value === 'string') return JSON.stringify(value);
  if (value === null) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  try {
    const serialized = JSON.stringify(value, pretty ? null : undefined, pretty ? 2 : undefined) ?? String(value);
    if (pretty) return serialized.length > 8_000 ? `${serialized.slice(0, 7_997)}...` : serialized;
    return serialized.length > 140 ? `${serialized.slice(0, 137)}...` : serialized;
  } catch {
    return String(value);
  }
}

function parseValue(value: string): JsonValue {
  const trimmed = value.trim();
  if (!trimmed) return '';
  if (trimmed === 'true') return true;
  if (trimmed === 'false') return false;
  const number = Number(trimmed);
  return Number.isFinite(number) && trimmed !== '' ? number : value;
}

function headersToText(value: JsonValue | undefined): string {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return '';
  return Object.entries(value).map(([key, raw]) => `${key}: ${typeof raw === 'string' ? raw : String(raw ?? '')}`).join('\n');
}

function parseHeaders(value: string): JsonObject {
  const headers: JsonObject = {};
  for (const line of value.split('\n')) {
    const separator = line.indexOf(':');
    if (separator <= 0) continue;
    const key = line.slice(0, separator).trim();
    if (key) headers[key] = line.slice(separator + 1).trim();
  }
  return headers;
}

function isJsonObject(value: JsonValue | undefined): value is JsonObject {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function GenericConfigFormNoForm({ locale }: { locale: Locale }) {
  return <p className="node-editor-form-empty">{t(locale, 'nodeNoForm')}</p>;
}
